use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::PathBuf;

#[derive(Debug)]
struct FloatArray {
    values: Vec<f32>,
}

#[derive(Debug)]
struct ConvEntry {
    channels: usize,
    num_filters: usize,
    is_depthwise: bool,
    is_pointwise: bool,
    with_relu: bool,
    weight_name: String,
    bias_name: String,
}

fn main() {
    let source_path = PathBuf::from("../src/facedetectcnn-data.cpp");
    println!("cargo:rerun-if-changed={}", source_path.display());

    let source = fs::read_to_string(&source_path).expect("read facedetectcnn-data.cpp");
    let arrays = parse_float_arrays(&source);
    let entries = parse_conv_entries(&source);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let generated_path = out_dir.join("model_data.rs");
    fs::write(generated_path, generate_model_data(&arrays, &entries)).expect("write model_data.rs");
}

fn parse_float_arrays(source: &str) -> HashMap<String, FloatArray> {
    let mut arrays = HashMap::new();
    let mut offset = 0;

    while let Some(relative_start) = source[offset..].find("float ") {
        let start = offset + relative_start + "float ".len();
        let Some(name_end) = source[start..].find('[') else {
            break;
        };
        let name = source[start..start + name_end].trim().to_string();
        let Some(equals_offset) = source[start + name_end..].find('=') else {
            break;
        };
        let equals = start + name_end + equals_offset;
        let Some(open_offset) = source[equals..].find('{') else {
            break;
        };
        let open = equals + open_offset;
        let Some(close_offset) = source[open..].find("};") else {
            break;
        };
        let close = open + close_offset;
        let body = &source[open + 1..close];
        let values = parse_float_values(body);

        arrays.insert(name, FloatArray { values });
        offset = close + 2;
    }

    arrays
}

fn parse_float_values(body: &str) -> Vec<f32> {
    body.split(',')
        .filter_map(|raw| {
            let value = raw.trim();
            if value.is_empty() {
                None
            } else {
                Some(parse_c_float(value))
            }
        })
        .collect()
}

fn parse_c_float(value: &str) -> f32 {
    let trimmed = value.trim_end_matches('f');
    trimmed
        .parse::<f32>()
        .unwrap_or_else(|error| panic!("parse float literal {value:?}: {error}"))
}

fn parse_conv_entries(source: &str) -> Vec<ConvEntry> {
    let table_start = source
        .find("ConvInfoStruct param_pConvInfo")
        .expect("find param_pConvInfo");
    let open = source[table_start..]
        .find('{')
        .map(|idx| table_start + idx)
        .expect("find param_pConvInfo open brace");
    let close = source[open..]
        .find("};")
        .map(|idx| open + idx)
        .expect("find param_pConvInfo close brace");
    let body = &source[open + 1..close];

    body.lines()
        .filter_map(|line| {
            let line = line.trim().trim_end_matches(',');
            if !line.starts_with('{') {
                return None;
            }
            let line = line.trim_start_matches('{').trim_end_matches('}');
            let parts: Vec<_> = line.split(',').map(str::trim).collect();
            assert_eq!(parts.len(), 7, "unexpected ConvInfo entry: {line}");

            Some(ConvEntry {
                channels: parts[0].parse().expect("channels"),
                num_filters: parts[1].parse().expect("num_filters"),
                is_depthwise: parse_bool(parts[2]),
                is_pointwise: parse_bool(parts[3]),
                with_relu: parse_bool(parts[4]),
                weight_name: parts[5].to_string(),
                bias_name: parts[6].to_string(),
            })
        })
        .collect()
}

fn parse_bool(value: &str) -> bool {
    match value {
        "true" => true,
        "false" => false,
        _ => panic!("unexpected bool literal {value:?}"),
    }
}

fn generate_model_data(arrays: &HashMap<String, FloatArray>, entries: &[ConvEntry]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by rust/build.rs from src/facedetectcnn-data.cpp\n");
    out.push_str("use crate::filter::{ConvInfo, FilterKind};\n");
    out.push_str("use crate::model::{Model, CONV_LAYER_COUNT};\n\n");

    let mut names: Vec<_> = arrays.keys().cloned().collect();
    names.sort();
    for name in names {
        let array = arrays.get(&name).expect("array by name");
        out.push_str(&format!(
            "static {}: [f32; {}] = [",
            rust_static_name(&name),
            array.values.len()
        ));
        for (idx, value) in array.values.iter().enumerate() {
            if idx % 12 == 0 {
                out.push('\n');
                out.push_str("    ");
            }
            out.push_str(&format!("{value:?}, "));
        }
        out.push_str("\n];\n\n");
    }

    out.push_str(&format!(
        "pub const STATIC_MODEL_LAYER_COUNT: usize = {};\n\n",
        entries.len()
    ));
    out.push_str("pub fn load_static_model() -> Model {\n");
    out.push_str("    let mut model = Model::with_capacity(CONV_LAYER_COUNT);\n");
    for entry in entries {
        validate_entry_arrays(arrays, entry);
        out.push_str("    model.add_filter(ConvInfo {\n");
        out.push_str(&format!("        channels: {},\n", entry.channels));
        out.push_str(&format!("        num_filters: {},\n", entry.num_filters));
        out.push_str(&format!(
            "        kind: FilterKind::{},\n",
            if entry.is_pointwise {
                "Pointwise"
            } else {
                "Depthwise"
            }
        ));
        out.push_str(&format!("        with_relu: {},\n", entry.with_relu));
        out.push_str(&format!(
            "        weights: &{},\n",
            rust_static_name(&entry.weight_name)
        ));
        out.push_str(&format!(
            "        biases: &{},\n",
            rust_static_name(&entry.bias_name)
        ));
        out.push_str("    });\n");
    }
    out.push_str("    model\n");
    out.push_str("}\n");

    out
}

fn validate_entry_arrays(arrays: &HashMap<String, FloatArray>, entry: &ConvEntry) {
    assert_ne!(
        entry.is_depthwise, entry.is_pointwise,
        "each filter must be exactly one kind"
    );
    let weights = arrays
        .get(&entry.weight_name)
        .unwrap_or_else(|| panic!("missing weights {}", entry.weight_name));
    let biases = arrays
        .get(&entry.bias_name)
        .unwrap_or_else(|| panic!("missing biases {}", entry.bias_name));
    let expected_weights = if entry.is_pointwise {
        entry.channels * entry.num_filters
    } else {
        entry.channels * 9
    };
    assert_eq!(
        weights.values.len(),
        expected_weights,
        "unexpected weight length for {}",
        entry.weight_name
    );
    assert_eq!(
        biases.values.len(),
        entry.num_filters,
        "unexpected bias length for {}",
        entry.bias_name
    );
}

fn rust_static_name(name: &str) -> String {
    name.to_ascii_uppercase()
}
