CXX := g++
OPENCV := opencv4
CXXFLAGS := -std=c++11 `pkg-config --cflags $(OPENCV)` 
LIBS := `pkg-config --libs $(OPENCV)`
SRC := $(wildcard *.cpp)
OBJ := $(SRC:%.cpp=%.o)

all: detect

detect: $(OBJ)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LIBS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $< -c -o $@

clean:
	rm *.o detect